user_initialize: q:/q10/spg/system_1/x86e_win64/obj/xtop.exe
user_initialize: +tkqcr:otk_detailing_03p90_spr15463139.qcr
user_initialize: +tkout:otk_detailing_03p90_spr15463139.out
user_initialize: +tkgrp:detailing
user_initialize: +tkid:03p90
qcr_file: otk_detailing_03p90_spr15463139.qcr
o_file: otk_detailing_03p90_spr15463139.out
group found: +tkgrp:detailing
OTKMAIN: group: detailing
QCR COMPARISON IS OK
